

export default [
    {
        id:0,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
    {
        id:1,
        price:34.67,
        title:"Pc re trucha que me encontre por ahi",
        description:`- MICRO: AMD DUAL CORE...
        - VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
        - MOTHER: GIGABYTE AMD E6010 Dual Core...
        - DISCO RIGIDO: NO CONTIENE...
        - DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
        - MEMORIA RAM: 8GB 1600MHZ DDR3...
        - GABINETE: ATX POWER KIT FUENTE 500W...
        - KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
        - MONITOR: LED WIDESCREEN 18.5...
        - SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,
        image:"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg"
    },
]