
import Product from "./js/product.js"


$(".cart-image").on("click",(e)=>{
    
    $(".sidebar").toggle(2000)
})


const shoppingCart=[];


const p = new Product(0,34.67,"Pc re trucha que me encontre por ahi",`- MICRO: AMD DUAL CORE...
- VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
- MOTHER: GIGABYTE AMD E6010 Dual Core...
- DISCO RIGIDO: NO CONTIENE...
- DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
- MEMORIA RAM: 8GB 1600MHZ DDR3...
- GABINETE: ATX POWER KIT FUENTE 500W...
- KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
- MONITOR: LED WIDESCREEN 18.5...
- SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg");

const p2 = new Product(0,34.67,"Pc re trucha que me encontre por ahi",`- MICRO: AMD DUAL CORE...
- VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
- MOTHER: GIGABYTE AMD E6010 Dual Core...
- DISCO RIGIDO: NO CONTIENE...
- DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
- MEMORIA RAM: 8GB 1600MHZ DDR3...
- GABINETE: ATX POWER KIT FUENTE 500W...
- KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
- MONITOR: LED WIDESCREEN 18.5...
- SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg");

const p3 = new Product(0,34.67,"Pc re trucha que me encontre por ahi",`- MICRO: AMD DUAL CORE...
- VIDEO: Gráficos Radeon R2 HD Graphics SoC (ONBOARD)...
- MOTHER: GIGABYTE AMD E6010 Dual Core...
- DISCO RIGIDO: NO CONTIENE...
- DISCO ESTADO SOLIDO: SSD 240GB SATA3 (5 VECES MAS RAPIDO)
- MEMORIA RAM: 8GB 1600MHZ DDR3...
- GABINETE: ATX POWER KIT FUENTE 500W...
- KIT: TECLADO USB, MOUSE USB Y PARLANTES POTENCIADOS...
- MONITOR: LED WIDESCREEN 18.5...
- SISTEMA OPERATIVO: WINDOWS 10 64bits TRIAL`,"https://infiniteconcepts.com/wp-content/uploads/computer-servers-and-workstations/Workstation.jpg");


const productView= document.getElementById("product-view");

const d=p.toHTML();
productView.appendChild(d)
productView.appendChild(p2.toHTML())
productView.appendChild(p3.toHTML())
console.log(d)
